[Anti2re] added ptrace functionality
teambi0s/secREtary pull request #30
Opened 2021-04-26 13:20 UTC by P-Vishnu-Madhav

2021-04-29 05:40 UTC, adityavardhanpadala commented
Looks like we are replacing the function call with a dummy function. But the issue I see here with this patching method is what would we do if the function's return value saved into a variable affects control flow of the tracee. @Freakston looks like we need to have another look at what all targets are we thinking to bypass using Anti2RE

2021-04-29 06:44 UTC, Freakston commented
The rest of the code looks fine. Do we proceed and merge it? We will have to look into this module at the end anyways. What do you guys say? @adityavardhanpadala @akulpillai

2021-04-29 06:46 UTC, Freakston requested changes
Please remove the binary

2021-04-29 06:46 UTC, Freakston commented on Anti2RE/makefile.rules
> +##############################################################
why delete and recreate files? just asking

2021-04-29 12:58 UTC, akulpillai commented
@Freakston yup, sounds good. Merge it after he removes the unwanted files

2021-11-07 23:24 UTC, akulpillai commented
this done?

2021-11-17 05:44 UTC, adityavardhanpadala commented
Nah it isn't. Not update on the pr after that

On Mon, Nov 8, 2021 at 4:54 AM Akul Pillai ***@***.***> wrote:

> this done?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/teambi0s/secREtary/pull/30#issuecomment-962701375>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKQRKF54VB2WYC7V5PKR7HLUK4DDNANCNFSM43S4AIIA>
> .
>

2021-12-30 07:51 UTC, akulpillai commented
close this? I assume this is redundant stuff from #32 ?

2021-12-31 09:13 UTC, adityavardhanpadala commented
okay

2021-12-31 09:13 UTC, closed without merging